### ISSUE TITLE
Solution benchmarking

### ISSUE THREAD

**Issue by Rekkonnect** [AlFasGD/AdventOfCSharp#3]
With the help of BenchmarkDotNet, the user should be able to optionally benchmark a selected problem, with given options. Flexibility does not need to come immediately out of the box, and more issues will be created for additional feature improvements.

**Comment by AlFasGD** [comment]
Current issues to be dealt with:

Given the structure of the project, benchmarking support is meant to be abstracted away and provide users the convenience of simply calling a method and have all their solutions be benchmarked, all through reflection from ProblemsIndex.

However, so far there is no known solution to this. This feature will probably have to be pushed back until a resolution is discovered, or BDN properly supports this flexibility.

**Comment by AlFasGD** [comment]
An alternative I'm considering is 
- source generators
- dynamic class creation through `System.Reflection.Emit`
